package storage

import (
	"fmt"
	"os"
	"path/filepath"
	"time"

	"github.com/glebarez/sqlite"
	"gorm.io/gorm"
	"gorm.io/gorm/logger"
)

// Store wraps a gorm DB handle and provides typed repository methods.
type Store struct {
	db *gorm.DB
}

// Open opens (creating if needed) the SQLite database at path and runs
// AutoMigrate for all models.
func Open(path string) (*Store, error) {
	if dir := filepath.Dir(path); dir != "." && dir != "" {
		if err := os.MkdirAll(dir, 0o755); err != nil {
			return nil, fmt.Errorf("storage: create db directory: %w", err)
		}
	}

	db, err := gorm.Open(sqlite.Open(path), &gorm.Config{
		Logger: logger.Default.LogMode(logger.Silent),
	})
	if err != nil {
		return nil, fmt.Errorf("storage: open db: %w", err)
	}
	if err := db.AutoMigrate(AllModels()...); err != nil {
		return nil, fmt.Errorf("storage: migrate: %w", err)
	}
	return &Store{db: db}, nil
}

// ErrNotFound is returned when a lookup finds no matching row.
var ErrNotFound = gorm.ErrRecordNotFound

// GetUserByTelegramID looks up a registered user by their Telegram ID.
// Returns ErrNotFound if nobody has registered with that ID yet.
func (s *Store) GetUserByTelegramID(telegramUserID int64) (*User, error) {
	var u User
	err := s.db.Where("telegram_user_id = ?", telegramUserID).First(&u).Error
	if err != nil {
		return nil, err
	}
	// Best-effort: keep the stored username fresh for display purposes.
	return &u, nil
}

// TouchUsername updates a user's cached Telegram username if it changed.
func (s *Store) TouchUsername(u *User, username string) {
	if username == "" || u.Username == username {
		return
	}
	u.Username = username
	s.db.Model(u).Update("username", username)
}

// CreateUser registers a new Telegram user with the given role. Callers are
// responsible for verifying the admin setup code or invite code first.
func (s *Store) CreateUser(telegramUserID int64, username string, role Role) (*User, error) {
	u := &User{TelegramUserID: telegramUserID, Username: username, Role: role}
	if err := s.db.Create(u).Error; err != nil {
		return nil, err
	}
	return u, nil
}

// HasAdmin reports whether an admin has already claimed the bot.
func (s *Store) HasAdmin() (bool, error) {
	var count int64
	if err := s.db.Model(&User{}).Where("role = ?", RoleAdmin).Count(&count).Error; err != nil {
		return false, err
	}
	return count > 0, nil
}

// CreateInviteCode persists a new invite code generated by an admin.
func (s *Store) CreateInviteCode(code string, createdByUserID uint, expiresAt time.Time) (*InviteCode, error) {
	ic := &InviteCode{Code: code, CreatedByUserID: createdByUserID, ExpiresAt: expiresAt}
	if err := s.db.Create(ic).Error; err != nil {
		return nil, err
	}
	return ic, nil
}

// GetActiveInviteCode finds an unused, unexpired invite code by its value.
func (s *Store) GetActiveInviteCode(code string) (*InviteCode, error) {
	var ic InviteCode
	err := s.db.Where("code = ? AND used_by_user_id IS NULL AND expires_at > ?", code, time.Now()).First(&ic).Error
	if err != nil {
		return nil, err
	}
	return &ic, nil
}

// MarkInviteCodeUsed records that an invite code was redeemed.
func (s *Store) MarkInviteCodeUsed(id uint, usedByUserID uint) error {
	now := time.Now()
	return s.db.Model(&InviteCode{}).Where("id = ?", id).Updates(map[string]interface{}{
		"used_by_user_id": usedByUserID,
		"used_at":         now,
	}).Error
}

// ListActiveInviteCodes returns unused, unexpired invite codes an admin
// generated.
func (s *Store) ListActiveInviteCodes(createdByUserID uint) ([]InviteCode, error) {
	var codes []InviteCode
	err := s.db.Where("created_by_user_id = ? AND used_by_user_id IS NULL AND expires_at > ?", createdByUserID, time.Now()).
		Order("created_at asc").Find(&codes).Error
	return codes, err
}

// RevokeInviteCode deletes an unused invite code so it can no longer be
// redeemed. Returns ErrNotFound if no matching unused code exists.
func (s *Store) RevokeInviteCode(code string) error {
	res := s.db.Where("code = ? AND used_by_user_id IS NULL", code).Delete(&InviteCode{})
	if res.Error != nil {
		return res.Error
	}
	if res.RowsAffected == 0 {
		return ErrNotFound
	}
	return nil
}

// CreateWallet persists a new wallet row.
func (s *Store) CreateWallet(w *Wallet) error {
	return s.db.Create(w).Error
}

// ListWallets returns all wallets owned by a user.
func (s *Store) ListWallets(userID uint) ([]Wallet, error) {
	var wallets []Wallet
	err := s.db.Where("user_id = ?", userID).Order("created_at asc").Find(&wallets).Error
	return wallets, err
}

// GetWalletByLabel finds a user's wallet by its label.
func (s *Store) GetWalletByLabel(userID uint, label string) (*Wallet, error) {
	var w Wallet
	err := s.db.Where("user_id = ? AND label = ?", userID, label).First(&w).Error
	if err != nil {
		return nil, err
	}
	return &w, nil
}

// GetWalletByAddress finds a user's wallet by its on-chain address.
func (s *Store) GetWalletByAddress(userID uint, address string) (*Wallet, error) {
	var w Wallet
	err := s.db.Where("user_id = ? AND address = ?", userID, address).First(&w).Error
	if err != nil {
		return nil, err
	}
	return &w, nil
}

// CreateToken persists a new deployed-token row.
func (s *Store) CreateToken(t *Token) error {
	return s.db.Create(t).Error
}

// ListTokens returns all tokens deployed by a user.
func (s *Store) ListTokens(userID uint) ([]Token, error) {
	var tokens []Token
	err := s.db.Where("user_id = ?", userID).Order("created_at asc").Find(&tokens).Error
	return tokens, err
}

// GetTokenByAddress finds a token this user deployed by contract address.
func (s *Store) GetTokenByAddress(userID uint, address string) (*Token, error) {
	var t Token
	err := s.db.Where("user_id = ? AND contract_address = ?", userID, address).First(&t).Error
	if err != nil {
		return nil, err
	}
	return &t, nil
}

// LogTransaction persists a transaction audit row.
func (s *Store) LogTransaction(t *Transaction) error {
	return s.db.Create(t).Error
}

// UpdateTransactionStatus updates the status/hash of a previously logged
// transaction.
func (s *Store) UpdateTransactionStatus(id uint, status TxStatus, txHash string) error {
	return s.db.Model(&Transaction{}).Where("id = ?", id).Updates(map[string]interface{}{
		"status":  status,
		"tx_hash": txHash,
	}).Error
}
